name: Check JSON on PR
on:
  pull_request:
    paths:
      - 'domains/**/*.json'

permissions:
  contents: read
  pull-requests: write # enable write permissions for pull request comments
  issues: write # pull requests are just issues with extra features

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: json-yaml-validate
        id: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.4.0
        with:
          base_dir: './domains'
          json_schema: '.github/workflows/domain-schema.json'
          comment: "true" # enable comment mode
          token: ${{ secrets.MY_GITHUB_TOKEN }} # Use your PAT
