name: Register domain
on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true  
    runs-on: ubuntu-latest
    steps:
      - uses: wei/curl@master
        with:
          args: https://amazing-api.3.us-1.fl0.io/update_domains
